highlighter: rouge
github: [Repository metadata]

baseurl: "https://kristenzirkler.github.io/optimal-health-volusion"
livereload: true

# cdn_path: ""
# production: true
encoding: utf-8

# Sass
sass:
  sass_dir: scss
  style: :compressed
  line_numbers: false